#####################################################################################
#        _____                          __  __                                      #
#       / ____|                        |  \/  |                                     #
#      | (___   ___ _ ____   _____ _ __| \  / | __ _ _ __   __ _  __ _  ___ _ __    #
#       \___ \ / _ \ '__\ \ / / _ \ '__| |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|   #
#       ____) |  __/ |   \ V /  __/ |  | |  | | (_| | | | | (_| | (_| |  __/ |      #
#      |_____/ \___|_|    \_/ \___|_|  |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|      #
#                                                                 __/ |             #
#         The Ultimate Server Managing Plugin                    |___/              #
#####################################################################################
#
# To enable or disable the following things type true or false between the ""
#
BlockPlacing: "true"
#
BlockBreaking: "true"
#
ItemDrop: "true"
#
Death: "true"
#
GameModeChange: "true"
#
PVP: "true"
#
Item Damage: "true"
#
Player Kicking: "true"
#
Sneaking: "true"
#
Achievements: "true"
#
Explosions: "true"
#
Inventory Open: "true"
#
Item Pickup: "true"
#
Item Crafting: "true"
#######################################################################################################################
