#####################################################################################
#        _____                          __  __                                      #
#       / ____|                        |  \/  |                                     #
#      | (___   ___ _ ____   _____ _ __| \  / | __ _ _ __   __ _  __ _  ___ _ __    #
#       \___ \ / _ \ '__\ \ / / _ \ '__| |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|   #
#       ____) |  __/ |   \ V /  __/ |  | |  | | (_| | | | | (_| | (_| |  __/ |      #
#      |_____/ \___|_|    \_/ \___|_|  |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|      #
#                                                                 __/ |             #
#         The Ultimate Server Managing Plugin                    |___/              #
#####################################################################################
#
# The Prefix of the messages sent to players from server manager
Prefix: &eServer&4Manager
#
BlockPlacing:
#
BlockBreaking:
#
Chatting:
#
ItemDrop:
#
Death:
#
GameModeChange:
#
Commands:
#
PVP:
#
Item Damage:
#
Player Kicking:
#
Player Respawning:
#
Sneaking:
#
Achievements:
#
Explosions:
#
Inventory Open:
#
Item Pickup:
#
Item Crafting:
#######################################################################################################################
